name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Enable node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
          run_install: true

      - name: TypeCheck
        run: pnpm tsc -b
      - name: Build
        run: pnpm nx affected --target=build --parallel=3
      - name: Test
        run: pnpm nx affected --target=test --parallel=2
      - name: Lint
        run: pnpm nx affected --target=lint --parallel=2
      - name: e2e
        run: pnpm nx affected --target=e2e --parallel=2
