name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pnpm
        run: |
          npm i -g pnpm
          pnpm set verify-store-integrity false

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: \${{ runner.os }}-\${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            \${{ runner.os }}-

      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: Version command
        id: version
        run: |
          pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: pnpm install
        run: |
          pnpm install

      - name: Push changes
        run: |
          git config user.email "github.serviceaccount@wanews.com.au"
          git config user.name "SWM GitHub Service Account"
          git add -A
          git commit -m "Version packages" || echo "No changes to commit"
          git push

      - name: typecheck
        run: pnpm tsc -b

      - name: Build packages
        run: pnpm run build

      - name: Lint types and code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm e2e

      - name: Release packages
        uses: changesets/action@master
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
